version: '3'

services:
  face-detection:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=8000
    tty: true
    volumes:
      - ".:/algorithms"
      - "/mnt/models/face_detection:/face_detection"
      - "/mnt/models/face_comparison:/face_comparison"
      - "/mnt/models/ssd:/ssd"
    stdin_open: true

